### ISSUE TITLE
linki

### ISSUE THREAD

**Issue by destag** [destag/IMIS-deep-learning#1]
wrzucamy linki

**Comment by SzymonGo** [comment]
https://www.cs.toronto.edu/~fritz/absps/imagenet.pdf - informacje na temat AlexNet

**Comment by SzymonGo** [comment]
http://pokazywarka.pl/t5znoh/#utm_medium=frame&utm_campaign=wyrzucenie_z_ramki&utm_source=www.wykop.pl - czcionka do tablic

**Comment by SzymonGo** [comment]
http://ai.stanford.edu/~jkrause/cars/car_dataset.html - zbiór samochodów i ich marek
